plugins {
    id 'java'
    id 'java-gradle-plugin'}

gradlePlugin {
    plugins {
        gametestable {
            id = 'gametestable'
            implementationClass = 'quilt.internal.plugin.GametestablePlugin'
        }
    }
}

tasks.named('jar') {
    dependsOn(rootProject.tasks.publishGametestablePublicationToGametestableRepository)
}

jar {
    manifest {
        attributes(
            'Implementation-Version': rootProject.version
        )
    }
}