pluginManagement {
    repositories {
        maven {
            name = 'Quilt'
            url = 'https://maven.quiltmc.org/repository/release'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        coreLibs {
            from(files("core/gradle/libs.versions.toml"))
        }
    }
}

includeBuild('core') {
    dependencySubstitution {
        // substitute module('org.quiltmc:quilt-mappings') using project(':')
        substitute module('org.quiltmc:gametest-verify') using project(':')
    }
}

include('gametest')
