pluginManagement {
    repositories {
        maven {
            name = 'Quilt'
            url = 'https://maven.quiltmc.org/repository/release'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }

    includeBuild('core')
}

dependencyResolutionManagement {
    versionCatalogs {
        coreLibs {
            from(files("core/gradle/libs.versions.toml"))
        }
    }
}

include('gametest')
