package quilt.internal.plugin;

import org.gradle.api.Action;
import org.gradle.api.Project;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.file.Directory;
import org.gradle.api.file.FileTree;
import org.gradle.api.plugins.PluginContainer;
import org.gradle.api.tasks.JavaExec;
import org.gradle.api.tasks.TaskCollection;
import org.gradle.api.tasks.TaskContainer;
import org.gradle.api.tasks.TaskProvider;
import org.jetbrains.annotations.NotNull;
import quilt.internal.constants.Constants;
import quilt.internal.constants.Classifiers;
import quilt.internal.constants.Extensions;
import quilt.internal.QuiltMappingsExtension;
import quilt.internal.plugin.abstraction.DefaultTaskedMappingsProjectPlugin;
import quilt.internal.task.build.AddProposedMappingsTask;
import quilt.internal.task.build.InvertPerVersionMappingsTask;
import quilt.internal.task.build.MappingsV2JarTask;
import quilt.internal.task.build.MergeTinyV2Task;
import quilt.internal.task.jarmapping.MapNamedJarTask;
import quilt.internal.task.jarmapping.MapPerVersionMappingsJarTask;
import quilt.internal.task.setup.ConstantsJarTask;
import quilt.internal.task.setup.DownloadMinecraftLibrariesTask;
import quilt.internal.task.unpick.CombineUnpickDefinitionsTask;
import quilt.internal.task.unpick.RemapUnpickDefinitionsTask;
import quilt.internal.task.unpick.UnpickJarTask;
import quilt.internal.task.unpick.gen.OpenGlConstantUnpickGenTask;
import quilt.internal.task.unpick.gen.UnpickGenTask;

import static quilt.internal.constants.Constants.PER_VERSION_MAPPINGS_NAME;
import static quilt.internal.constants.Constants.UNPICK_NAME;

/**
 * {@linkplain TaskContainer#register Registers} tasks that output mappings in Quilt's v2 format.
 * <p>
 * Applies:
 * <ul>
 *     <li> {@link QuiltMappingsBasePlugin}
 *     <li> {@link MinecraftJarsPlugin}
 *     <li> {@link MapMinecraftJarsPlugin}
 * </ul>
 * Additionally:
 * <ul>
 *     <li> creates the {@value UNPICK_CONFIGURATION_NAME} {@link Configuration}
 *     <li> adds the the {@value UNPICK_CONFIGURATION_NAME} {@link Configuration} to
 *          {@linkplain TaskCollection#configureEach(Action) each} {@link UnpickJarTask}s'
 *          {@link JavaExec#classpath(Object...) classpath};<br>
 *          {@value UNPICK_CONFIGURATION_NAME} must include {@link daomephsta.unpick.cli.Main}
 *          and its dependencies in order to use {@link UnpickJarTask}s
 *    <li> {@linkplain TaskCollection#configureEach(Action) configures}
 *          the following defaults for {@link MappingsV2JarTask}s:
 *          <ul>
 *              <li> {@link MappingsV2JarTask#getUnpickMeta() unpickMeta}: {@link QuiltMappingsExtension}'s
 *                   {@link QuiltMappingsExtension#getUnpickMeta() unpickMeta}
 *              <li> {@link MappingsV2JarTask#getUnpickDefinition() unpickDefinition}:
 *                   {@link CombineUnpickDefinitionsTask}'s {@link CombineUnpickDefinitionsTask#getOutput() output}
 *          </ul>
 * </ul>
 *
 * Note: v2 {@value Constants#INTERMEDIARY_MAPPINGS_NAME} mappings are created by {@link MapIntermediaryPlugin} tasks.
 */
public abstract class MapV2Plugin extends DefaultTaskedMappingsProjectPlugin<MapV2Plugin.Tasks> {
    public static final String UNPICK_CONFIGURATION_NAME = UNPICK_NAME;

    @Override
    protected Tasks applyImpl(@NotNull Project project) {
        final Configuration unpick = project.getConfigurations().create(UNPICK_CONFIGURATION_NAME);

        // apply required plugins and save their registered objects
        final PluginContainer plugins = project.getPlugins();

        final QuiltMappingsExtension ext = plugins.apply(QuiltMappingsBasePlugin.class).getExt();

        final MinecraftJarsPlugin.Tasks minecraftJarsTasks =
            plugins.apply(MinecraftJarsPlugin.class).getTasks();
        final TaskProvider<DownloadMinecraftLibrariesTask> downloadMinecraftLibraries =
            minecraftJarsTasks.downloadMinecraftLibraries();

        final MapMinecraftJarsPlugin.Tasks mapMinecraftJarsTasks =
            plugins.apply(MapMinecraftJarsPlugin.class).getTasks();
        final TaskProvider<MapPerVersionMappingsJarTask> mapPerVersionMappingsJar =
            mapMinecraftJarsTasks.mapPerVersionMappingsJar();
        final TaskProvider<InvertPerVersionMappingsTask> invertPerVersionMappings =
            mapMinecraftJarsTasks.invertPerVersionMappings();
        final TaskProvider<AddProposedMappingsTask> insertAutoGeneratedMappings =
            mapMinecraftJarsTasks.insertAutoGeneratedMappings();

        // register this plugin's tasks
        final TaskContainer tasks = project.getTasks();

        final var mergeTinyV2 = tasks.register(
            MergeTinyV2Task.MERGE_TINY_V_2_TASK_NAME,
            MergeTinyV2Task.class,
            task -> {
                // TODO this used to be dependent on v2UnmergedMappingsJar, but afaict it has no effect on this task

                task.getInput().convention(
                    insertAutoGeneratedMappings.flatMap(AddProposedMappingsTask::getOutputMappings)
                );

                task.getHashedTinyMappings().convention(
                    invertPerVersionMappings.flatMap(InvertPerVersionMappingsTask::getInvertedTinyFile)
                );

                task.getOutputMappings().convention(
                    this.provideMappingsBuildFile("merged2." + Extensions.TINY)
                );
            }
        );

        tasks.register(
            OpenGlConstantUnpickGenTask.OPEN_GL_UNPICK_GEN_TASK_NAME,
            OpenGlConstantUnpickGenTask.class,
            task -> {
                task.getPerVersionMappingsJar().convention(
                    mapPerVersionMappingsJar.flatMap(MapPerVersionMappingsJarTask::getOutputJar)
                );

                task.getArtifactsByName().convention(
                    downloadMinecraftLibraries.flatMap(DownloadMinecraftLibrariesTask::getArtifactsByName)
                );

                task.getUnpickGlStateManagerDefinitions().convention(
                    this.provideMappingsBuildFile(UNPICK_NAME + "_glstatemanager." + Extensions.UNPICK)
                );

                task.getUnpickGlDefinitions().convention(
                    this.provideMappingsBuildFile(UNPICK_NAME + "_gl." + Extensions.UNPICK)
                );
            }
        );

        final var combineUnpickDefinitions = tasks.register(
            CombineUnpickDefinitionsTask.COMBINE_UNPICK_DEFINITIONS_TASK_NAME,
            CombineUnpickDefinitionsTask.class,
            task -> {
                task.getUnpickDefinitions().from(project.getTasks().withType(UnpickGenTask.class));

                task.getOutput().convention(
                    this.provideMappingsBuildFile("definitions." + Extensions.UNPICK)
                );
            }
        );

        final var remapUnpickDefinitions = tasks.register(
            RemapUnpickDefinitionsTask.REMAP_UNPICK_DEFINITIONS_TASK_NAME,
            RemapUnpickDefinitionsTask.class,
            task -> {
                task.getInput().convention(combineUnpickDefinitions.flatMap(CombineUnpickDefinitionsTask::getOutput));

                task.getMappings().convention(mergeTinyV2.flatMap(MergeTinyV2Task::getOutputMappings));

                task.getOutput().convention(
                    this.provideMappingsBuildFile(PER_VERSION_MAPPINGS_NAME + "-definitions." + Extensions.UNPICK)
                );
            }
        );

        // constants are configured in build.gradle because they're from a project source set
        final var constantsJar = tasks.register(ConstantsJarTask.CONSTANTS_JAR_TASK_NAME, ConstantsJarTask.class);

        tasks.withType(UnpickJarTask.class).configureEach(task -> {
            task.classpath(unpick);

            task.getInputFile().convention(
                mapPerVersionMappingsJar.flatMap(MapPerVersionMappingsJarTask::getOutputJar)
            );

            task.getDecompileClasspathFiles().from(
                downloadMinecraftLibraries.flatMap(DownloadMinecraftLibrariesTask::getLibrariesDir)
                    .map(Directory::getAsFileTree)
                    .map(FileTree::getFiles)
            );
        });

        final var unpickHashedJar = tasks.register(
            UnpickJarTask.UNPICK_HASHED_JAR_TASK_NAME,
            UnpickJarTask.class,
            task -> {
                task.getUnpickDefinition().convention(
                    remapUnpickDefinitions.flatMap(RemapUnpickDefinitionsTask::getOutput)
                );

                task.getUnpickConstantsJar().set(constantsJar.flatMap(ConstantsJarTask::getArchiveFile));

                task.getOutputFile().convention(
                    this.provideMappedMinecraftBuildFile(ext.provideSuffixedMinecraftVersion(
                        "-" + Classifiers.PER_VERSION_UNPICKED + "." + Extensions.JAR
                    ))
                );
            }
        );

        final var mapNamedJar = tasks.register(
            MapNamedJarTask.MAP_NAMED_JAR_TASK_NAME,
            MapNamedJarTask.class,
            task -> {
                task.getInputJar().convention(unpickHashedJar.flatMap(UnpickJarTask::getOutputFile));

                task.getMappingsFile().convention(
                    insertAutoGeneratedMappings.flatMap(AddProposedMappingsTask::getOutputMappings)
                );

                task.getOutputJar().convention(
                    this.provideMappedMinecraftBuildFile(ext.provideSuffixedMinecraftVersion(
                        "-" + Classifiers.NAMED + "." + Extensions.JAR
                    ))
                );
            }
        );

        tasks.withType(MappingsV2JarTask.class).configureEach(task -> {
            task.getUnpickMeta().convention(ext.getUnpickMeta());

            task.getUnpickDefinition().convention(
                combineUnpickDefinitions.flatMap(CombineUnpickDefinitionsTask::getOutput)
            );
        });

        {
            final var v2UnmergedMappingsJar = tasks.register(
                MappingsV2JarTask.V2_UNMERGED_MAPPINGS_JAR_TASK_NAME,
                MappingsV2JarTask.class,
                ext.getUnpickVersion()
            );
            v2UnmergedMappingsJar.configure(task -> {
                task.getMappings().convention(
                    insertAutoGeneratedMappings.flatMap(AddProposedMappingsTask::getOutputMappings)
                );

                task.getArchiveClassifier().convention(Classifiers.V2);
            });
        }

        final var v2MergedMappingsJar = tasks.register(
            MappingsV2JarTask.V2_MERGED_MAPPINGS_JAR_TASK_NAME,
            MappingsV2JarTask.class,
            ext.getUnpickVersion()
        );
        v2MergedMappingsJar.configure(task -> {
            task.getMappings().convention(mergeTinyV2.flatMap(MergeTinyV2Task::getOutputMappings));

            task.getArchiveClassifier().convention(Classifiers.MERGED_V2);
        });

        return new Tasks(mergeTinyV2, unpickHashedJar, mapNamedJar);
    }

    public record Tasks(
        TaskProvider<MergeTinyV2Task> mergeTinyV2,
        TaskProvider<UnpickJarTask> unpickHashedJar,
        TaskProvider<MapNamedJarTask> mapNamedJar
    ) { }
}
