plugins {
    id 'java'
    id 'gametestable'
    alias rootLibs.plugins.fabric.loom
}

loom {
    runs {
        gametest {
            name 'Game Test'
            source sourceSets.main

            server()

            ideConfigGenerated(true)
        }
    }
}

repositories {
    maven {
        name = 'gametest'
        url = '../build/gametestable'
    }
}

dependencies {
    minecraft(rootLibs.minecraft)
    mappings "org.quiltmc:quilt-mappings:${gametestable.version}:intermediary-v2"

    modImplementation rootLibs.fabric.loader
    // modImplementation rootLibs.fabric.api
}

processResources {
    final expanding = [
        version: gametestable.version,
        group: 'org.quilt.internal',
        minecraft_version: rootLibs.versions.minecraft.get(),
        fabric_loader_version: rootLibs.versions.fabric.loader.get(),
    ]

    inputs.properties(expanding)

    filesMatching('fabric.mod.json') {
        expand expanding
    }
}

// mod test data isn't loaded without fapi, so copy it to a datapack
final copyDataToDatapack = tasks.register('copyDataToDatapack', Copy) {
    from 'src/main/resources/data'
    into 'run/world/datapacks/gametests/data'

    final packRoot = destinationDir.toPath().parent

    outputs.dir(packRoot)

    doFirst {
        packRoot.deleteDir()
        packRoot.toFile().mkdirs()
        packRoot.resolve('pack.mcmeta').toFile().text =
            """\
            {
              "pack": {
                "description": "Test Game",
                "pack_format": 74
              }
            }
            """.stripIndent()
    }
}

tasks.named('runGametest') {
    dependsOn copyDataToDatapack
}
