plugins {
    id 'java'
    id 'gametestable'
    alias libs.plugins.quilt.loom
}

repositories {
    maven {
        name = 'gametest'
        url = '../core/build/gametestable'
    }
}

dependencies {
    minecraft(coreLibs.minecraft)

    mappings "org.quiltmc:gametestable-quilt-mappings:${gametestable.version}:intermediary-v2"
}
