name: 'PR Manager'
description: 'Update labels, FCP status, and other data for mappings PRs.'
inputs:
  github-token:
    description: 'Github Token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
