[versions]
fabric_loom = "1.10.1"

fabric_loader = "0.16.12"
fabric_api = "0.119.6+1.21.5"

[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

[bundles]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
