package quilt.internal.tasks.jarmapping;

import java.util.Map;

import quilt.internal.Constants;
import quilt.internal.tasks.build.AddProposedMappingsTask;
import quilt.internal.tasks.setup.DownloadMinecraftLibrariesTask;

public class MapNamedJarTask extends MapJarTask {
    public static final String TASK_NAME = "mapNamedJar";

    public MapNamedJarTask() {
        super(Constants.Groups.MAP_JAR_GROUP, Constants.PER_VERSION_MAPPINGS_NAME, "named");

        getInputs().files(getTaskByName(DownloadMinecraftLibrariesTask.TASK_NAME).getOutputs().getFiles().getFiles());

        inputJar.convention(() -> fileConstants.unpickedJar);
        mappingsFile.convention(() -> this.<AddProposedMappingsTask>getTaskByName("insertAutoGeneratedMappings").getOutputMappings());
        outputJar.convention(() -> fileConstants.namedJar);

        this.dependsOn("mergeTinyV2", "unpickHashedJar");
    }

    public Map<String, String> getAdditionalMappings() {
        return Map.of(
                "javax/annotation/Nullable", "org/jetbrains/annotations/Nullable",
                "javax/annotation/Nonnull", "org/jetbrains/annotations/NotNull",
                "javax/annotation/concurrent/Immutable", "org/jetbrains/annotations/Unmodifiable"
        );
    }
}

