name: 'Update base'
description: 'Update the base branch for a pull request to the default branch'
inputs:
  github-token:
    description: 'Github Token'
    required: true
  pull-number:
    description: 'Pull Request number'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
