name: Generate Diff
on: [push]
jobs:
  diff:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: gradle/wrapper-validation-action@v2
      - name: Decompile sources and create diff
        run: ./gradlew lazilyDiffTarget
      - name: Check Diff Created
        id: check-diff-created
        uses: andstor/file-existence-action@v3
        with:
          files: "build/target.diff"
      - name: Create diff comment
        uses: ./.github/actions/diff-uploader/
        if: ${{ matrix.java == 21 }}
        id: diff-uploader
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-src-exists: ${{ steps.check-diff-created.outputs.files_exists }}
      - name: Upload diff
        if: hashFiles('target.diff') != ''
        uses: actions/upload-artifact@v4
        with:
          name: Diff
          path: target.diff
